services:
  qb-connection-monitor:
    image: qbittorrent-connection-monitor:latest
    container_name: ghcr.io/oscariremma/qbittorrent-connection-monitor:latest
    environment:
      - QBIT_ENDPOINT=http://qbittorrent:8080/
      - QBIT_USERNAME=admin
      - QBIT_PASSWORD=adminadmin
      - QBIT_CHECK_INTERVAL=60
      - QBIT_RETRY_INTERVAL=5
      - QBIT_SHUTDOWN_WAIT=30
    networks:
      - qbittorrent

  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    networks:
      - qbittorrent

networks:
  qbittorrent: